### PR TITLE
Fix: #102 회원탈퇴 hard delete 방식으로 변경

### PR DESCRIPTION
**Pull request by LeeJae-H**

### CODE REVIEW

**Comment by LeeJae-H** [comment]
1-1. ALTER TABLE picture_generate_request_picture_user_face
	DROP FOREIGN KEY FKn3eevxsc1g2y9066gec3nc6gr;
1-2. ALTER TABLE picture_generate_request_picture_user_face
    	ADD CONSTRAINT 
        FOREIGN KEY (user_face_picture_list_id) REFERENCES picture_user_face (id)
        ON DELETE CASCADE;
     
2-1. ALTER TABLE picture_pose
	DROP FOREIGN KEY FK8bgg3d74k2450lm9cpq7c43x6;
2-2. ALTER TABLE picture_pose
	ADD CONSTRAINT
	FOREIGN KEY (uploaded_by) REFERENCES users (id)
	ON DELETE CASCADE;

3-1. ALTER TABLE picture_generate_request
	DROP FOREIGN KEY FK9q3w2d1jclp83piy7pfykg7no;
3-2. ALTER TABLE picture_generate_request
	ADD CONSTRAINT 
	FOREIGN KEY (requester_id) REFERENCES users (id)
	ON DELETE CASCADE;

4-1. ALTER TABLE picture_completed
	DROP FOREIGN KEY FKc52flwtrxribkqdwwlg6q6ijf;
4-2. ALTER TABLE picture_completed
	ADD CONSTRAINT 
	FOREIGN KEY (requester_id) REFERENCES users(id)
	ON DELETE CASCADE;

5-1. ALTER TABLE report
	DROP FOREIGN KEY FKide3gruwmi3na8jjsgfs04din;
5-2. ALTER TABLE report
	ADD CONSTRAINT
	FOREIGN KEY (created_by) REFERENCES users(id)
	ON DELETE CASCADE;      
		    
6-1. ALTER TABLE picture_generate_response
	DROP FOREIGN KEY FKona6rc453j5q7jm4vn46q96vo;
6-2. ALTER TABLE picture_generate_response
	ADD CONSTRAINT 
	FOREIGN KEY (request_id) REFERENCES picture_generate_request (id)
	ON DELETE CASCADE;
    
7-1. ALTER TABLE settlement
	DROP FOREIGN KEY FKp0ihds2oyvjijgxhb6o2787o2;
7-2. ALTER TABLE settlement
	ADD CONSTRAINT 
	FOREIGN KEY (picture_generate_response_id)
	REFERENCES picture_generate_response(id)
	ON DELETE CASCADE;
	
8-1. ALTER TABLE report
	DROP FOREIGN KEY FKs3b67lfte8p9b2yipm2ehe6i;
8-2. ALTER TABLE report
	ADD CONSTRAINT 
	FOREIGN KEY (picture_generate_response_id)
	REFERENCES picture_generate_response(id)
	ON DELETE CASCADE;
	
9-1. ALTER TABLE picture_created_by_creator
	DROP FOREIGN KEY FKtktafmri06k6x5ebf5i8yqnib;
9-2. ALTER TABLE picture_created_by_creator
	ADD CONSTRAINT 
	FOREIGN KEY (picture_generate_response_id)
	REFERENCES picture_generate_response(id)
	ON DELETE CASCADE;
	
10-1. ALTER TABLE picture_generate_request_picture_user_face
	DROP FOREIGN KEY FKdi7o8e7ri34u9uplqktn0bs3l;
10-2. ALTER TABLE picture_generate_request_picture_user_face
	ADD CONSTRAINT 
	FOREIGN KEY (picture_generate_request_id)
	REFERENCES picture_generate_request(id)
	ON DELETE CASCADE;
	
위 쿼리들을 모두 실행해야 정상 작동합니다...!

**Comment by BYEONGRYEOL** [comment]
관련해서 JPA에서 같은 옵션을 주고싶거든요, domain 모듈에서도 수정되어야할거같습니다

**Comment by LeeJae-H** [comment]
위의 쿼리문에 따른 수정 내역입니다.

1. 수정 x
2. User 수정
3. User 수정
4. User 수정
5. BaseEntity 수정
6. PictureGenerateRequest 수정
7. 수정 x
8. PictureGenerateResponse 수정
9. 수정 x
10. 수정 x

**Comment by BYEONGRYEOL** [comment]
떙큐!!!!!!!!!1

**Pull request merged**
